spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/mrjeff}
    username: ${USERNAME:postgres}
    password: ${PASSWORD:admin}
  jpa.properties.hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    jdbc.lob.non_contextual_creation: true